Output showcase.gif

Set FontSize 46
Set Width 1080
Set Height 720

Type "cd /home/space/IPA-API/"
Enter
Type "./ipa.sh"
Sleep 200ms
Enter
Sleep 200ms
Type@300ms bilaplo
Sleep 2000ms
Enter
Sleep 1000ms
Type "./ipa.sh"
Sleep 200ms
Enter
Sleep 200ms
Type@200ms lesbilaplo
Sleep 500ms
Enter
Sleep 500ms
Type "./ipa.sh"
Sleep 200ms
Enter
Sleep 200ms
Type@200ms clomifron
Sleep 500ms
Enter
Sleep 500ms
Type "./ipa.sh"
Sleep 200ms
Enter
Sleep 200ms
Type@200ms clomifronunr
Sleep 500ms
Enter
Sleep 500ms


