#!/usr/bin/bash

cat $(dirname "$0")/src/main.json | \
jq -r ".letters" | \
head -n -1 | tail -n +2 | \
sed 's/^ *//;s/\",//g;s/\"//g' | \
column -ts ':' | \
(
  if [[ -n $1 ]]; then
    fzf --filter="$1" | head -n 1
  else
    fzf
  fi
) | \
awk '{print $2}'
